export const CHAT_SHOW = "CHAT_SHOW";
export const CHAT_HIDE = "CHAT_HIDE";
export const CHAT_CHANNEL_SHOW = "CHAT_CHANNEL_SHOW";
export const CHAT_CHANNEL_HIDE = "CHAT_CHANNEL_HIDE";
export const CHAT_SET_CHANNEL_ID = "CHAT_SET_CHANNEL_ID";