export const MAP_ADD_MARKER = "MAP_ADD_MARKER";
export const MAP_SHOW_MARKER_MODAL = "MAP_SHOW_MARKER_MODAL";
export const MAP_HIDE_MARKER_MODAL = "MAP_HIDE_MARKER_MODAL";
export const MAP_SET_LAST_LOC = "MAP_SET_LAST_LOC";
export const MAP_SET_MARKERS = "MAP_SET_MARKERS";