export const MAP_SET_CURR_LOC = "MAP_SET_CURR_LOC";
export const MAP_PUSH_MARKER = "MAP_PUSH_MARKER";
export const MAP_SET_FROM_DB = "MAP_SET_FROM_DB";
export const MAP_UPDATE_TEXT = "MAP_UPDATE_TEXT";