export const LISTINGS_HIDE = "LISTINGS_HIDE";
export const LISTINGS_SHOW = "LISTINGS_SHOW";
export const LISTING_INFO_SHOW = "LISTING_INFO_SHOW";
export const LISTING_INFO_HIDE = "LISTING_INFO_HIDE";
export const LISTING_INFO_SET_ID = "LISTING_INFO_SET_ID";